### PR TITLE
Add minimum zoom, fix white outline styling

### LINKED ISSUE #118: Limit zoom distance on the map
we don't want people zooming out all the way

### PR DESCRIPTION
**Pull request by hanlinc27**
Super tiny changes:
Deleted weird zoom out: (prev) 
image
Deleted top white space
image
Closes #123

### CODE REVIEW

**Comment by lesliexin** [comment]
ty for fixing the whitespace!

File: ui/src/pages/ShoeMap.tsx [hunk 1]
```diff
@@ -15,6 +16,7 @@ const MapContainer = styled.div`
   height: 100%;
   width: 100%;
   display: flex;
+
```
Comment (lesliexin) [inline ui/src/pages/ShoeMap.tsx:19]: extra space

File: ui/src/pages/ShoeMap.tsx [hunk 2]
```diff
@@ -36,13 +38,15 @@ const markerList = [
...
+  const minZoom = 3;
+  const maxZoom = 18;
   const currentLocation = { lat: 43.4723, lng: -80.5449 };
   const [isDrawerOpen, setIsDrawerOpen] = useState(StoryDrawerState.Closed);
 
   return (
     <React.Fragment>
       <MapContainer>
-        <StyledMap center={currentLocation} zoom={zoom} zoomControl={false}>
+        <StyledMap center={currentLocation} zoom = {zoom} minZoom= { minZoom } maxZoom = {maxZoom} zoomControl={false}>
```
Comment (lesliexin) [inline ui/src/pages/ShoeMap.tsx]: spaces between curly braces

**Review by lesliexin — APPROVED** [review]
smol lint fixes :)
