### PR TITLE
Fix linter errors

### LINKED ISSUE #76: Fix linting issues in Go code

### PR DESCRIPTION
**Pull request by aspensantos**
Closes #76

### CODE REVIEW

File: cmd/server.go [hunk 1]
```diff
@@ -78,7 +78,9 @@ var (
 				}
 			}
 
-			zap.L().Sync() // flush the logger
+			if err := zap.L().Sync(); err != nil { // flush the logger
+				logger.Fatalw("Could not flush logger", "Err", err)
```
Comment (dhillondeep) [inline cmd/server.go]: Since we are dealing with logger closing, we should not print error using logger. Instead we should do:
```go
fmt.Fprint(os.Stderr, "Could not flush logger", err.Error())
```

File: restapi/rest/http.go [hunk 2]
```diff
@@ -13,7 +13,9 @@ type routeHandler func(w http.ResponseWriter, r *http.Request) render.Renderer
 // Custom ServeHTTP that handlers custom render errors
 func (fn routeHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 	if renderer := fn(w, r); renderer != nil {
-		render.Render(w, r, renderer)
+		if err := render.Render(w, r, renderer); err != nil {
+			http.Error(w, err.Error(), 500)
```
Comment (dhillondeep) [inline restapi/rest/http.go]: use `http.StatusInternalServerError` instead of typing error code as a number

**Review by dhillondeep — CHANGES_REQUESTED** [review]

**Review by dhillondeep — APPROVED** [review]
