### PR TITLE
Bug fix: filter on map page only shows countries from visible stories

### LINKED ISSUE #341: Filter showing countries not visible on map
The filter on the main map currently shows countries that are attached stories that are set to be not visible.
image

### PR DESCRIPTION
**Pull request by DinuWije**
## Description
- Current behaviour: The filter on the homepage page currently shows countries that are attached to stories that are not visible on the map (ie. you can filter by the country, but when you do nothing shows up on the map)
- Created a fix + ran a short test

### CODE REVIEW

File: restapi/authors.go [hunk 1]
```diff
@@ -37,24 +36,14 @@ func (api api) CreateAuthors(w http.ResponseWriter, r *http.Request) render.Rend
...
+	var countries []string
 
-	for _, entry := range authors {
-		if entry.OriginCountry != "" {
-			countries[entry.OriginCountry] = true
-		} else {
-			api.logger.Debug("Empty origin country")
-		}
-	}
+    err := api.database.Table("stories").Where("is_visible = true").Distinct().Pluck("author_country", &countries).Error
```
Comment (nimwijetunga) [inline restapi/authors.go:41]: Can you leave a comment here indicating the SQL query:
`SELECT DISTINCT author_country from stories where is_visble=true`

Gorm is not that intuitive so this could be helpful for people reading this code

**Review by nimwijetunga — APPROVED** [review]
lgtm

File: restapi/authors.go (hunk 1 above)
Comment (AbhiPrasad) [inline restapi/authors.go:41]: Does the `Distinct()` call make sure there are no duplicate countries here?

File: restapi/endpoints_test.go [hunk 2]
```diff
@@ -345,6 +345,24 @@ func (suite *endpointTestSuite) TestGetAllStories() {
 	response.Object().Value("payload").Array().Element(1).Object().Value("current_city").Equal("Toronto")
 	response.Object().Value("payload").Array().Element(1).Object().Value("tags").Array().Empty()
 }
+
+func (suite *endpointTestSuite) TestGetVisibleCountries() {
```
Comment (AbhiPrasad) [inline restapi/endpoints_test.go:349]: I'd like to see a test to make sure that no duplicate countries are returned.

File: restapi/authors.go (hunk 1 above)
Comment (nimwijetunga) [reply restapi/authors.go:41]: Yeah the equivalent query is `SELECT DISTINCT author_country from stories where is_visble=true` (https://gorm.io/docs/advanced_query.html#Pluck) but i agree the test should check for this

File: restapi/endpoints_test.go (hunk 2 above)
Comment (DinuWije) [reply restapi/endpoints_test.go:349]: I think this test covers it because there are two stories with the Country as France, but only one of them shows up in the returned array. Note that array size is confirmed to be 3, not 4 (showing that there are no such duplicates) 
--> `[Canada, France, US]`
