### PR TITLE
fix: make image optional in edit story

### LINKED ISSUE #253: Fix: Change image in edit story optional

### PR DESCRIPTION
**Pull request by Shehryar21**
closes #253

### CODE REVIEW

File: restapi/stories.go [hunk 1]
```diff
@@ -130,16 +130,16 @@ func (api api) EditStoryByID(w http.ResponseWriter, r *http.Request) render.Rend
...
-	imageURL, err := api.uploadImageTos3(file, h.Size, h.Filename)
-	if err != nil {
-		return rest.ErrInvalidRequest(api.logger, "Error uploading the image to s3.", err)
+	if err == nil {
+		imageURL, err = api.uploadImageTos3(file, h.Size, h.Filename)
+		if err != nil {
+			return rest.ErrInvalidRequest(api.logger, "Error uploading the image to s3.", err)
+		}
 	}
-	defer file.Close()
```
Comment (nimwijetunga) [inline restapi/stories.go:142]: don't we still need to close the file if there was an image?

**Review by nimwijetunga — APPROVED** [review]
lgtm. Just test this on a story with an image just to be sure before merging

File: restapi/stories.go (hunk 1 above)
Comment (Shehryar21) [reply restapi/stories.go:142]: this actually defers the closing of file. We dont need this cuz we are not really writing to the file, so we can close it.
