### PR TITLE
fix: visibility search and bracket space

### LINKED ISSUE #320: Cannot sort individual columns on visible stories
# Description
In the main stories dashboard, the visible stories tab is unable to be sorted by each column. Clicking it does not provide the same behaviour as pending map changes and all stories.
0b14e87c-06a7-4db6-9f7c-8921e264f30d
# Steps to Reproduce
Navigate to the visible stories tab, click on the sort option in the table's header.

# Potential Solution
Look in the table in `/admin/AllStories/index` and check the data type (is it `StoryView`) for the` tabValue={1}` and check if the correct ID's are passed for sort.

### LINKED ISSUE #324: Unnecessary spaces on tab names and buttons
# Description

Spaces between numbers and brackets (see below) on tabs and buttons

# Steps to Reproduce

1. navigate to all stories page
2. observe all stories, visible stories and pending map changes tabs
3. select story(ies) with checkboxes
4. observe hide all from map/show all on map buttons

# Potential Solution

cc Hanlin and Jeff
Screen Shot 2021-04-27 at 9 34 54 PM

### PR DESCRIPTION
**Pull request by hanlinc27**
### Description
Bug fix: reduce the bracket space for the buttons on dashboard. 
**To test:
9ef1c967-edc9-4c14-90b4-a713d55f44ae
** Please make sure you're able to sort individual columns in the visible stories tab.

Closes #320 
Closes #324

### CODE REVIEW

File: ui/src/pages/Admin/AllStories/index.tsx [hunk 1]
```diff
@@ -235,24 +235,25 @@ export const AllStories: React.FC = () => {
     undefined
   );
   const classes = useStyles();
-  const allStoriesLabel = `${"ALL STORIES"} ${"("} ${
+  const allStoriesLabel = `${"ALL STORIES"} ${"("}${
```
Comment (Shehryar21) [inline ui/src/pages/Admin/AllStories/index.tsx]: why not just have it like this: ``All STORIES (${state.origTableData.length})`` so much cleaner

**Review by Shehryar21 — APPROVED** [review]

**Review by nimwijetunga — APPROVED** [review]
works for me
