### PR TITLE
randomize location, fix date styling, fix drawer content styling

### LINKED ISSUE #151: bug: Zoom in on pin cluster when clicked
Right now it looks like (Interaction 1/2)
ezgif com-gif-maker (1)

But we would like it to look like the last pin cluster click.
image (1)

### PR DESCRIPTION
**Pull request by hanlinc27**
@dhillondeep should fix the spiral issue?
### Description
Thoughts on randomizing the coordinates slightly on the client side so that the clusters can be zoomed in?
Closes #151 
cluster

Preview date styling: 
image

Add in the new lines on story drawer content: 
image

### CODE REVIEW

File: ui/src/components/PinPreview.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ export function PinPreview({
           Read Full Story
         </StyledButton>
         <CardDetailText>
-          {author} • {date}
+          {author} • {date.substring(0,4)}
```
Comment (hanlinc27) [inline ui/src/components/PinPreview.tsx]: So that only shows the year - but I think we're changing this in the DB anyways?

Comment (dhillondeep) [reply ui/src/components/PinPreview.tsx]: yeah we will just have a year as a field in database

**Review by dhillondeep — APPROVED** [review]
This looks awesome! We should get this merged. It also fixes text formatting issues soo that is nice

File: ui/src/components/Pin.tsx [hunk 2]
```diff
@@ -59,7 +65,10 @@ export function Pin({
   });
 
   return (
-    <Marker position={[story.latitude, story.longitude]} icon={icon}>
+    <Marker
+      position={[randomCoords(story.latitude), randomCoords(story.longitude)]}
```
Comment (AbhiPrasad) [inline ui/src/components/Pin.tsx:69]: This doesn't make them unique though, there can still be instances where the positions are the same. Should we guard against those?

Comment (hanlinc27) [reply ui/src/components/Pin.tsx:69]: I kind of don't like this solution at all to be honest since it makes the viewing experience inconsistent, it's just sort of a hacky way to get the clustering working properly. I think in the future we should either
1) let the user place the pin where they would like in a specific city
2) have them enter a general city location, geocode, and then pick somewhere [random ](https://gis.stackexchange.com/questions/25877/generating-random-locations-nearby)within a specific radius? 

We could also make it ordered and just have it fan out directionally from the original coordinate but I don't think that would look as nice. For now, I think since it's a temporary fix, the chances of it not being unique is very, very small?

Comment (dhillondeep) [reply ui/src/components/Pin.tsx:69]: I agree with hanlin on this. We need a fresh design of how coordinates are handled and shown. Current way could work for few stories but when number of stories increase, we could see major trouble. Since the term is finishing I guess this fix could work and next term we could add a proper solution

**Review by AbhiPrasad — APPROVED** [review]

File: ui/src/components/PinPreview.tsx [hunk 3]
```diff
@@ -72,7 +72,7 @@ export function PinPreview({
           Read Full Story
         </StyledButton>
         <CardDetailText>
-          {author} • {date}
+          {author} • {date.substring(0, 4)}
```
Comment (lesliexin) [inline ui/src/components/PinPreview.tsx]: [nit] if we're getting the `createdAt` value as a typescript `Date` object can we use `dateObj.getYear()` instead?

**Review by lesliexin — APPROVED** [review]
🚀

File: ui/src/components/PinPreview.tsx (hunk 3 above)
Comment (hanlinc27) [reply ui/src/components/PinPreview.tsx]: I think I'm just going to revert it entirely since Deep is changing it in the database to just year so it can just fetch it as a string
